// Fotos reales de referencia (Wikimedia Commons, licencias libres) por tipo de artículo.
// Se cargan desde internet; si no hay conexión se muestra la ilustración. Al conectar el
// sistema de pañol, la foto propia de cada artículo (campo `foto`) tiene prioridad.
const T = 'https://thumb.wikimedia.org/wikipedia/commons/thumb/';
const U = 'https://upload.wikimedia.org/wikipedia/commons/';
const th = (p: string, f: string) => `${T}${p}/${f}/500px-${f}`;
export interface Photo { u: string; autor: string; lic: string; titulo: string }
const P = (u: string, autor: string, lic: string, titulo: string): Photo => ({ u, autor, lic, titulo });

export const PHOTOS: Record<string, Photo> = {
  pads: P(th('9/92', 'Brake_pad.jpg'), 'A7N8X', 'CC BY-SA 3.0', 'Brake pad.jpg'),
  disc: P(th('c/c4', 'Ventilated_2-Piece_Floating_Disc_Curved_Drilled_%26_Slotted_Brake_Rotor.jpg'), 'Atharv Chandel', 'CC BY 4.0', 'Ventilated 2-Piece Floating Disc Brake Rotor.jpg'),
  filter: P(th('c/cb', 'Engine_oil_filter.JPG'), 'Dvortygirl', 'CC BY-SA 3.0', 'Engine oil filter.JPG'),
  airfilter: P(th('b/b3', '2014_Filtr_powietrza_DEMCiflex.jpg'), 'Jacek Halicki', 'CC BY 3.0', '2014 Filtr powietrza DEMCiflex.jpg'),
  belt: P(th('d/d2', 'Keilrippenriemen_Servopumpe_Spannrollen_VW_T4_IMG_20160922_135213.jpg'), 'Hans Haase', 'CC BY-SA 4.0', 'Keilrippenriemen VW T4.jpg'),
  clutch: P(th('0/03', 'Kupplungsscheibe2.jpg'), 'M.james', 'Dominio público', 'Kupplungsscheibe2.jpg'),
  pump: P(th('f/fa', 'Kuehlmittelpumpe_Suzuki_G10A.jpg'), 'Thilo Parg', 'CC BY-SA 3.0', 'Kuehlmittelpumpe Suzuki G10A.jpg'),
  bushing: P(th('1/1c', 'Silentblock_500_1.jpg'), 'Cav', 'Dominio público', 'Silentblock 500 1.jpg'),
  alternator: P(th('f/ff', 'Car_alternator_on_a_workbench_surrounded_by_various_auto_parts_in_a_garage_setting.jpg'), 'Shixart1985', 'CC BY 2.0', 'Car alternator on a workbench.jpg'),
  starter: P(th('8/83', 'Automobile_starter.JPG'), 'Willdre', 'CC BY-SA 3.0', 'Automobile starter.JPG'),
  battery: P(th('4/4c', 'Car_battery.jpg'), 'Azorbli', 'CC BY-SA 4.0', 'Car battery.jpg'),
  bulb: P(`${U}3/3d/Lampe_h4.jpg`, 'Digi-pex', 'CC BY-SA 4.0', 'Lampe h4.jpg'),
  relay: P(`${U}8/8f/AutomotiveRelay.jpg`, 'Leonard G.', 'CC SA 1.0', 'AutomotiveRelay.jpg'),
  sensor: P(th('0/02', 'ABS_Sensor_GM_IMG_0557.JPG'), 'Hans Haase', 'CC BY-SA 4.0', 'ABS Sensor GM.JPG'),
  cable: P(th('f/f9', 'Wire_harness_for_aftermarket_head_unit.jpeg'), 'Zuzu', 'CC BY-SA 3.0', 'Wire harness.jpeg'),
  impact: P(th('9/97', 'Impact_wrench_01.jpg'), 'Bushytails', 'CC BY-SA 3.0', 'Impact wrench 01.jpg'),
  torque: P(th('9/9a', 'Click-torque-wrench.jpg'), 'Wikimedia Commons', 'CC BY-SA 3.0', 'Click-torque-wrench.jpg'),
  jack: P(th('5/51', 'Denzel_hydraulic_bottle_jack.jpg'), 'Denzel-llc', 'CC BY-SA 4.0', 'Denzel hydraulic bottle jack.jpg'),
  sockets: P(th('2/26', 'Socket_set_with_two_ratchets_in_box_%28photographed_on_snow%29.jpeg'), 'Pittigrilli', 'CC BY-SA 4.0', 'Socket set with two ratchets in box.jpeg'),
  multimeter: P(th('a/a6', 'Digital_Multimeter_Aka.jpg'), 'André Karwath', 'CC BY-SA 2.5', 'Digital Multimeter Aka.jpg'),
  depth: P(th('d/df', 'Profiltiefenmessger%C3%A4t_digital.JPG'), 'Fahi', 'CC BY-SA 3.0', 'Profiltiefenmessgerät digital.JPG'),
  extinguisher: P(th('3/3d', 'Fire_Extinguisher_ABC.jpg'), 'TPaign', 'CC BY-SA 4.0', 'Fire Extinguisher ABC.jpg'),
  firstaid: P(th('3/30', 'First-aid_travel_kit_1.jpg'), 'Renée Kools', 'CC BY 4.0', 'First-aid travel kit 1.jpg'),
  chock: P(th('c/ce', 'Unterlegkeil-1.JPG'), 'UlrichHeither', 'CC BY-SA 3.0', 'Unterlegkeil-1.JPG'),
  screen: P(th('c/c7', 'Destination_sign_on_Movia_bus_line_8A.jpg'), 'Leif Jørgensen', 'CC BY-SA 4.0', 'Destination sign on Movia bus.jpg'),
  gloves: P(`${U}8/8d/Disposable_nitrile_glove.jpg`, 'Wikimedia Commons', 'Dominio público', 'Disposable nitrile glove.jpg'),
  glasses: P(th('f/f0', '2023_Okulary_ochronne_%281%29.jpg'), 'Jacek Halicki', 'CC BY-SA 4.0', '2023 Okulary ochronne (1).jpg'),
  boots: P(th('5/52', 'DeWalt_Newark_steel_toe_work_boots.jpg'), 'Best For My Feet', 'CC BY 3.0', 'Steel toe work boots.jpg'),
  earmuff: P(th('e/e4', 'Peltor_earmuffs.jpg'), 'JiriMatejicek', 'CC BY-SA 4.0', 'Peltor earmuffs.jpg'),
  cloth: P(th('8/87', 'Microfibre_cloth.jpg'), 'Polyesterchen', 'Dominio público', 'Microfibre cloth.jpg'),
  bags: P(th('2/2d', 'Black_garbage_bag.jpg'), 'Wiki Farazi', 'Dominio público', 'Black garbage bag.jpg'),
  paintcan: P(th('1/1a', 'Ripolin_snel_primer_tin_can%2C_pic2.JPG'), 'Alf van Beem', 'CC0', 'Ripolin primer tin can.JPG'),
  putty: P(th('0/03', 'Spachtelmasse_IMG_20160715_14165.jpg'), 'Hans Haase', 'CC BY-SA 4.0', 'Spachtelmasse.jpg'),
  sandpaper: P(th('9/90', 'Schleifpapier_verschiedene_Sorten.jpg'), 'Simon Eugster', 'CC BY-SA 3.0', 'Schleifpapier verschiedene Sorten.jpg'),
  drum: P(th('b/bf', 'Castrol_oil_barrel_in_Athens_%282018%29.png'), 'Filippos Fragkogiannis', 'CC BY-SA 4.0', 'Castrol oil barrel (2018).png'),
  bucket: P(th('5/5e', '020220816_121314_motor_oil_Galkar.jpg'), 'Silar', 'CC BY-SA 4.0', 'Motor oil Galkar.jpg'),
  bottle: P(th('6/6f', 'L%C3%ADquido_para_frenos_Bardahl_DOT_3%2C_1000cc.jpg'), 'Just a Man', 'CC BY 4.0', 'Líquido para frenos Bardahl DOT 3.jpg'),
  bolt: P(th('c/c0', 'Wheel_Nuts_All_Details.png'), 'Davidtlchow', 'CC BY-SA 4.0', 'Wheel Nuts All Details.png'),
  nut: P(th('c/c1', 'Hexagon_nut.jpg'), 'Wasiul Bahar', 'CC BY-SA 4.0', 'Hexagon nut.jpg'),
  clamp: P(`${U}7/7c/Hose_clamp.jpg`, 'Valinor4', 'Dominio público', 'Hose clamp.jpg'),
  screws: P(`${T}2/29/Self_drilling_screw.tiff/lossless-page1-500px-Self_drilling_screw.tiff.png`, 'Susan Wright', 'Dominio público', 'Self drilling screw.tiff'),
  washer: P(th('b/b0', 'Bolt%2C_Plain_washer_and_Spring_lock_washer.jpg'), 'andersen_mrjh', 'CC BY-SA 2.0', 'Bolt, plain washer and spring lock washer.jpg'),
  tire: P(th('5/58', 'No_51_Continental_Tire_truck_tire_detail.jpg'), 'Spheroidite', 'CC BY-SA 4.0', 'Continental truck tire detail.jpg'),
  tireRetread: P(th('3/3c', 'Runderneuerte_Reifen26.jpg'), 'BattKkk', 'CC BY-SA 4.0', 'Runderneuerte Reifen26.jpg'),
  windshield: P(th('0/05', 'Stagecoach_bus_32630_%28P630PGP%29_-_Flickr_16331452041.jpg'), 'Ed Webster', 'CC BY 2.0', 'Stagecoach bus 32630.jpg'),
  window: P(th('e/e5', 'Mercedes-Benz_O-407_country_bus_window_side_ZOB_Hannover_Germany.jpg'), 'Christian A. Schröder', 'CC BY-SA 4.0', 'Mercedes-Benz O-407 bus window side.jpg'),
  rearglass: P(th('4/4e', 'Reflections_School_Bus_Rear_Window.jpg'), 'Tomwsulcer', 'CC0', 'School Bus Rear Window.jpg'),
  mirror: P(th('1/19', 'Bus_driver_seen_from_rear-view_mirror.jpg'), 'kunst.ftf', 'CC BY 2.0', 'Bus rear-view mirror.jpg'),
  valve: P(th('1/1e', 'Tire_Valve_Stem.jpg'), 'Andrew Pertsev', 'CC0', 'Tire Valve Stem.jpg'),
  patch: P(th('a/a7', 'Puncture-repaire-kit.jpg'), 'Björn Appel', 'CC BY-SA 3.0', 'Puncture repair kit.jpg'),
  tube: P(th('3/33', 'Changing_an_inner_tube_-_Adjusting_the_tire_%282%29.jpg'), 'Fanny Schertzer', 'CC BY-SA 3.0', 'Changing an inner tube.jpg'),
  gauge: P(`${U}8/80/Tire_pressure_gauge.jpg`, 'U.S. Air Force', 'Dominio público', 'Tire pressure gauge.jpg'),
  weights: P(th('7/7b', 'Schlaggewicht_Typ_161_HOFMANN_POWER_WEIGHT.jpg'), 'Teresa Herbert', 'CC BY-SA 4.0', 'Schlaggewicht HOFMANN.jpg'),
  cutdisc: P(th('a/aa', 'Winkelschleifer_Trennscheibe_Metall.jpg'), 'Ralf Pfeifer', 'CC BY-SA 4.0', 'Winkelschleifer Trennscheibe Metall.jpg'),
  electrode: P(th('8/8f', 'Types_of_welding_electrode.jpg'), 'Ghasemimoshref', 'CC BY-SA 4.0', 'Types of welding electrode.jpg'),
  tape: P(th('d/d0', 'Electrical-tape_black.jpg'), 'Jonas Bergsten', 'Dominio público', 'Electrical tape black.jpg'),
  rag: P(th('9/97', 'Texture_of_blue_cleaning_cloth.JPG'), 'Philippe Alès', 'CC BY-SA 3.0', 'Blue cleaning cloth.JPG'),
  silicone: P(th('4/45', 'Silicone_sealant_02.jpg'), 'Vis M', 'CC BY-SA 4.0', 'Silicone sealant 02.jpg'),
  spray: P(th('1/1a', 'Can_of_WD-40_%28100ml%29_%2853753418908%29.jpg'), 'qulolup', 'CC0', 'Can of WD-40.jpg'),
};
